//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayerOrPayee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public int PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
